# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-03 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompLearningApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='owner_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
